# Úkoly

## Ndarray
1. Jak zjistit velikost paměti libovolného pole. Vyzkoušejte na `a = np.array([1, 2, 3])`. Ozkoušejte s různou specifikací datového typu (`dtype` např. `np.int32`, `np.float64`, `np.complex128`).


In [2]:
import numpy as np
a = np.array([1, 2, 3], dtype=np.int32)
b = np.array([1, 2, 3], dtype=np.float64)
c = np.array([1, 2, 3], dtype=np.complex128)
print(a)
print(b)
print(c)

[1 2 3]
[1. 2. 3.]
[1.+0.j 2.+0.j 3.+0.j]



2. Zjistěte rozměry, velikost v jednotlivých rozměrech a celkový počet prvků v poli `a`.


In [4]:
print(a.ndim)
print(a.shape)
print(a.size)

1
(3,)
3



3. Zjistěte typ prvků v poli `a` a velikost jednoho prvku v bajtech.


In [6]:
print(a.dtype)
print(a.itemsize)

int32
4



4. Vytvořte NumPy pole s názvem `b` o stejných rozměrech jako `a`, ale s typem `np.float32`.


In [9]:
b = np.array(a, dtype=np.float32)
b

array([1., 2., 3.], dtype=float32)


5. Přetypujte pole `a` na typ `np.float32` a uložte do pole `c`.


In [10]:
c = a.astype(np.float32)
c

array([1., 2., 3.], dtype=float32)


6. Vytvořte pole `d` s typem `np.datetime64` a uložte do něj datum "2023-12-01".


In [12]:
d = np.array("2023-12-01", np.datetime64)
d

array('2023-12-01', dtype='datetime64[D]')


7. Vytvořte pole `e` s typem složeným ze dvou sloupců: `int32` a `string_` s maximální délkou 10 znaků.


In [32]:
muj_typ = np.dtype([("číslo", np.int32), ("text", np.string_, 10)])
e = np.array([], dtype=muj_typ)
e

array([], dtype=[('číslo', '<i4'), ('text', 'S10')])


8. Naplňte pole `e` hodnotami: `[(1, "a"), (2, "b"), (3, "c")]`.


In [33]:
e = [(1, "a"), (2, "b"), (3, "c")]
e

[(1, 'a'), (2, 'b'), (3, 'c')]


9. Změňte hodnotu druhého prvku v druhém sloupci pole `e` na "hello".


In [34]:
e["text"][1] = "hello"
e

TypeError: list indices must be integers or slices, not str

## Vytváření polí
1. Vytvořte matici samých jedniček o rozměrech 3x3. Vypište všechny její prvky.

In [35]:
A = np.ones((3, 3))
A

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

2. Vytvořte vektor s hodnotami od 10 do 49.


In [37]:
v = np.arange(10, 50)
v

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

3. Vytvořte pole 3x4 typu `bool` se všemi prvky `True`.


In [40]:
B = np.full((3, 4), True, dtype=np.bool8)
B

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

4. Vytvořte matici 3x3 s hodnotami od 0 do 8.


In [44]:
C = np.arange(0, 9).reshape(3, 3)
C

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

5. Vytvořte jednotkovou matici 3x3.


In [45]:
I = np.eye(3, 3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

6. Vytvořte pole 3x3x3 s náhodnými hodnotami.


In [47]:
R = np.random.rand(3, 3, 3)
R

array([[[0.75631367, 0.03456712, 0.22550735],
        [0.39631135, 0.54925007, 0.60606469],
        [0.49845211, 0.78330025, 0.30855906]],

       [[0.3114011 , 0.87080796, 0.52726698],
        [0.25316874, 0.98891141, 0.95627049],
        [0.0496338 , 0.10455184, 0.25331   ]],

       [[0.61193765, 0.30078867, 0.37894079],
        [0.06180331, 0.66242945, 0.37581527],
        [0.98413908, 0.04631669, 0.73174949]]])

7. Vytvořte 2D pole s 1 na okraji a 0 uvnitř.


In [60]:
M = np.zeros((5, 5))

8. Jak přidat okraj (vyplněný nulami) kolem existujícího pole?


In [65]:
N = np.pad(M, 1, constant_values=1)
N

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

9. Vytvořte matici 5x5 kde jediné nenulová prvky jsou [1, 2, 3, 4] pod hlavní diagonálou (nápověda - podívejte se na nápovědu funkce `diagflat`).
```
0 0 0 0 0
1 0 0 0 0
0 2 0 0 0
0 0 3 0 0 
0 0 0 4 0
```


In [54]:
H = np.diagflat(np.arange(1, 5), -1)
H

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

10. Z pole 8x8 samých nul vyvořte pomocí řezů co nejelegantnějším způsobem 8x8 matici, která vypadá jako šachovnice.
```
0 1 0 1 0 1 0 1
1 0 1 0 1 0 1 0
0 1 0 1 0 1 0 1
1 0 1 0 1 0 1 0
0 1 0 1 0 1 0 1
1 0 1 0 1 0 1 0
0 1 0 1 0 1 0 1
1 0 1 0 1 0 1 0
```


In [71]:
S = np.zeros((8, 8))
S[1::2, ::2] = 1
S[::2, 1::2] = 1
S

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

11. Vytvořte šachovnicovou matici 8x8 pomocí funkce "tile".


In [66]:
Š = np.tile(np.array([[0, 1], [1, 0]]), (4, 4))
Š

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

12. Vytvořte vektor velikosti 10 s hodnotami v rozsahu od 0 do 1 (obě hodnoty vyloučeny).


In [ ]:
u = np.linspace(0, 1, 12)[1:-1]
u

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

13. Vytvořte strukturované pole s koordináty x a y pokrývající oblast [0,1]x[0,1].


In [79]:
X, Y = np.meshgrid(u, u)
print(X)
print(Y)

[[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
  0.63636364 0.72727273 0.81818182 0.90909091]
 [0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
  0.63636364 0.72727273 0.81818182 0.90909091]
 [0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
  0.63636364 0.72727273 0.81818182 0.90909091]
 [0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
  0.63636364 0.72727273 0.81818182 0.90909091]
 [0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
  0.63636364 0.72727273 0.81818182 0.90909091]
 [0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
  0.63636364 0.72727273 0.81818182 0.90909091]
 [0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
  0.63636364 0.72727273 0.81818182 0.90909091]
 [0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
  0.63636364 0.72727273 0.81818182 0.90909091]
 [0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
  0.63636364

## Numpy a práce se soubory

1. Jak přečíst následující soubor?
   ```
   1, 2, 3, 4, 5
   6, , , 7, 8
    , , 9,10,11
   ```





In [80]:
%%writefile test_data.csv
1, 2, 3, 4, 5
6, , , 7, 8
 , , 9,10,11

Writing test_data.csv


In [84]:
data = np.genfromtxt("test_data.csv", int, delimiter=",", filling_values=0)
print(data)

[[ 1  2  3  4  5]
 [ 6  0  0  7  8]
 [ 0  0  9 10 11]]


2. Vytvořte tři náhodné matice 5x5 a uložte je do souboru pomocí formátu hdf5.

In [86]:
import h5py

A = np.random.rand(5, 5)
B = np.random.rand(5, 5)
C = np.random.rand(5, 5)

with h5py.File("matice.hdf5", "w") as soubor:
    soubor.create_dataset("matice_A", data=A)
    soubor.create_dataset("matice_B", data=B)
    soubor.create_dataset("matice_C", data=C)

3. Načtěte soubor z předchozího úkolu, zobrazte obsah každé matice a zjistěte jejich rozměry.

In [89]:
with h5py.File("matice.hdf5", "r") as soubor:
    A = soubor["matice_A"][:]
    print(A, A.shape)
    B = soubor["matice_B"][:]
    print(B, B.shape)
    C = soubor["matice_C"][:]
    print(C, C.shape)

[[0.4498819  0.74231084 0.60421987 0.18254374 0.57688834]
 [0.76580965 0.38264301 0.69488518 0.16362811 0.08113846]
 [0.91228463 0.39619666 0.94972554 0.33725781 0.02600907]
 [0.41052543 0.21044287 0.13169577 0.29733053 0.38782795]
 [0.22081318 0.19535142 0.34852016 0.577873   0.9495925 ]] (5, 5)
[[0.01706974 0.0801739  0.88830196 0.21918644 0.17128503]
 [0.65652192 0.71511329 0.3101438  0.21429526 0.41552347]
 [0.67846127 0.39071728 0.52033232 0.3658164  0.34046192]
 [0.79873257 0.89135193 0.58754507 0.58121678 0.68183756]
 [0.4200078  0.96401844 0.45104228 0.60451176 0.12087705]] (5, 5)
[[0.0172246  0.14130298 0.06290026 0.9625929  0.65269751]
 [0.70343525 0.33057686 0.2293471  0.75841815 0.68659412]
 [0.29113653 0.65111582 0.68699855 0.52967592 0.27112748]
 [0.34048856 0.63455193 0.36476919 0.60673114 0.55559366]
 [0.45210612 0.81486244 0.32678749 0.56321432 0.81513192]] (5, 5)
