# Úkoly

## Indexování a řezání

- Vytvořte NumPy pole s názvem `a` obsahující čísla od 1 do 10.
- Vytvořte 2D NumPy pole s názvem `b` o rozměrech 3x3 a naplňte ho libovolnými čísly.


In [46]:
import numpy as np
a = np.arange(1, 11)
b = np.random.randint(-9, 10, (3, 3)) # :D
print(a)
print(b)

[ 1  2  3  4  5  6  7  8  9 10]
[[-8 -5 -5]
 [ 2  7  6]
 [ 9  2  6]]



1. Vyberte z pole `a` třetí a čtvrtý prvek.


In [6]:
a[3:5]

array([4, 5])


2. Vyberte z pole `a` všechny sudá čísla.


In [8]:
a[1::2]

array([ 2,  4,  6,  8, 10])


3. Obraťte vektor `a` (první prvek se stane posledním).


In [9]:
a[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])


5. Vyberte z pole `b` druhý řádek.


In [47]:
b[1]

array([2, 7, 6])


6. Vyberte z pole `b` diagonální prvky.


In [48]:
print(b[np.eye(b.shape[0], dtype=bool)]) # řezem
print(np.diag(b)) # funkcí

[-8  7  6]
[-8  7  6]



7. Změňte hodnotu prvku na druhém řádku, prvním sloupci v `b` na 100.


In [49]:
b[1, 0] = 100


8. Vyberte z pole `b` všechny prvky větší než 5.


In [57]:
print(b[np.reshape([i > 5 for i in b.flat], b.shape)]) # kulantní řešení
print(b[b > 5]) # Pythonova zkratka

[100   7   6   9   6]
[100   7   6   9   6]



9. Vytvořte masku pro pole `b`, která bude True pro všechny prvky menší než 3.


In [58]:
maska = b < 3


10. Pomocí masky vyberte z pole `b` všechny prvky menší než 3.




In [59]:
b[maska]

array([-8, -5, -5,  2])


## View a copy

- Vytvořte NumPy pole s názvem `a` a naplňte ho libovolnými čísly.


In [62]:
a = np.random.randint(-9, 10, (5, 5))
print(a)

[[ 0  9  3  6  9]
 [-9 -9  1  8 -2]
 [ 7 -7  5 -4 -7]
 [-1 -8 -3  1  2]
 [ 4 -8  0 -3  7]]



1. Pomocí `a` vytvořte proměnnou `b` obsahující řez druhého řádku a všech sloupců pole `a`.


In [64]:
b = a[1]
print(b)

[-9 -9  1  8 -2]



3. Změňte hodnotu prvního prvku v `b`. Jak se tato změna projeví v `a`?


In [82]:
b[0] = 10
print(b)
print(a)

[10 -9  1  8 -2]
[[ 0  9  3  6  9]
 [10 -9  1  8 -2]
 [ 7 -7  5 -4 -7]
 [-1 -8 -3  1  2]
 [ 4 -8  0 -3  7]]



4. Vytvořte proměnnou `c` obsahující **kopii** druhého řádku pole `a`.


In [83]:
c = np.copy(a[1])
print(c)

[10 -9  1  8 -2]



5. Změňte hodnotu prvního prvku v `c`. Jak se tato změna projeví v `a`?


In [91]:
c[0] = 20
print(c)
print(a)

[20 -9  1  8 -2]
[[ 0  9  3  6  9]
 [10 -9  1  8 -2]
 [ 7 -7  5 -4 -7]
 [-1 -8 -3  1  2]
 [ 4 -8  0 -3  7]]



6. Zjistěte, zda `b` a `c` sdílí stejná data v paměti.


In [102]:
print(id(b.data) == id(c.data))

True



7. Vytvořte proměnnou `d` obsahující diagonální prvky pole `a`.


In [97]:
d = np.diagflat(np.diag(a))
print(d)

[[ 0  0  0  0  0]
 [ 0 -9  0  0  0]
 [ 0  0  5  0  0]
 [ 0  0  0  1  0]
 [ 0  0  0  0  7]]



8. Změňte hodnotu prvního diagonálního prvku v `d`. Jak se tato změna projeví v `a`?



In [98]:
d[0, 0] = 30
print(d)
print(a)

[[30  0  0  0  0]
 [ 0 -9  0  0  0]
 [ 0  0  5  0  0]
 [ 0  0  0  1  0]
 [ 0  0  0  0  7]]
[[ 0  9  3  6  9]
 [10 -9  1  8 -2]
 [ 7 -7  5 -4 -7]
 [-1 -8 -3  1  2]
 [ 4 -8  0 -3  7]]


9. Vytvořte proměnnou `e` obsahující transpozici pole `a`. Jak je to s pamětí, jedná se o kopii nebo o "array view" ověřte pomocí atributu base.


In [101]:
e = a.transpose()
print(id(e.base) == id(a))

True




## Lineární algebra

1. Vynásobte matici 5x3 maticí 3x2 (maticový součin).


In [103]:
A = np.random.rand(5, 3)
B = np.random.rand(3, 2)

print(A)
print(B)
print(A @ B)

[[0.70468176 0.40780655 0.88933343]
 [0.99043247 0.23337183 0.14759629]
 [0.0471873  0.58444725 0.56788499]
 [0.38057055 0.1016915  0.48785482]
 [0.09376679 0.3707156  0.12674947]]
[[0.31611122 0.5596086 ]
 [0.67503516 0.57808189]
 [0.50042701 0.72058261]]
[[0.94308804 1.27092976]
 [0.54448218 0.79551787]
 [0.69362387 0.77347284]
 [0.43308369 0.62329626]
 [0.34331566 0.35811014]]


2. Vezměme náhodnou matici 10x2 představující kartézské souřadnice, převeďte je na polární souřadnice.


In [105]:
kartezske = np.random.rand(10, 2)
print(kartezske)

komplexni = kartezske[:, 0] + kartezske[:, 1] * 1j
polarni = np.reshape([np.abs(komplexni), np.angle(komplexni)], (10, 2))
print(polarni)

[[0.91010439 0.01121942]
 [0.20409529 0.17902773]
 [0.66496626 0.04881413]
 [0.87500411 0.71298476]
 [0.06252001 0.5418064 ]
 [0.37379997 0.50077627]
 [0.28110435 0.3838078 ]
 [0.58758557 0.42864965]
 [0.8944473  0.75889042]
 [0.42907814 0.71053551]]
[[0.91017354 0.27148815]
 [0.66675554 1.12870699]
 [0.54540162 0.62490263]
 [0.47573951 0.72732202]
 [1.17300923 0.83004142]
 [0.01232699 0.72006176]
 [0.073277   0.68372198]
 [1.45591264 0.92957683]
 [0.93864873 0.63025814]
 [0.70359132 1.02752881]]


3. Vzhledem ke dvěma polím X a Y zkonstruujte Cauchyho matici C (Cij =1/(xi - yj)).


In [108]:
X = np.random.rand(3)
Y = np.random.rand(4)

C = np.zeros((X.shape[0], Y.shape[0]))
for i, x in enumerate(X):
    for j, y in enumerate(Y):
        C[i, j] = 1/(x*(i+1) - y*(j+1))

print(X)
print(Y)
print(C)

[0.94046769 0.32406274 0.3298255 ]
[0.72883679 0.73655855 0.80986472 0.07088067]
[[  4.72520807  -1.87740749  -0.67153463   1.52219747]
 [-12.38983692  -1.21213352  -0.5613346    2.74271081]
 [  3.83671398  -2.06765105  -0.69438771   1.41652329]]


4. Uvažujme náhodný vektor o tvaru (100,2) představující souřadnice, najděte vzdálenosti bod po bodu.


In [112]:
body = np.random.rand(100, 2)
# print(body)

vzdalenosti = np.zeros((100, 100))
for i, (x1, y1) in enumerate(body):
    for j, (x2, y2) in enumerate(body):
        vzdalenosti[i, j] = np.sqrt((x1-x2)**2 + (y1-y2)**2)

print(vzdalenosti)

[[0.         0.75360748 0.41352137 ... 0.3583777  0.42559202 0.53797113]
 [0.75360748 0.         0.51712033 ... 0.39522984 0.3969472  0.22884498]
 [0.41352137 0.51712033 0.         ... 0.27408773 0.13235543 0.40150733]
 ...
 [0.3583777  0.39522984 0.27408773 ... 0.         0.16802206 0.18725861]
 [0.42559202 0.3969472  0.13235543 ... 0.16802206 0.         0.26952708]
 [0.53797113 0.22884498 0.40150733 ... 0.18725861 0.26952708 0.        ]]


5. Ověřte empiricky na náhodné matici, že platí $(AB)^T = B^T A^T$


In [120]:
n = 10
A = np.random.rand(n, n)
B = np.random.rand(n, n)
print(B.T @ A.T - (A @ B).T)
print(np.allclose(B.T @ A.T, (A @ B).T))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
True


6. Pro náhodné 1D vektory $u, v$ vypočítejte dyadický součin $uv$ $$(uv)_{ij} = u_iv_j$$ pomocí `newaxis`. Zkontrolujte s `np.outer(u, v)`


In [125]:
u = np.random.rand(n)
v = np.random.rand(n)
print(u)
print(v)

uv = np.zeros((n, n))
for i, u1 in enumerate(u):
    for j, v1 in enumerate(v):
        uv[i, j] = u1 * v1
print(uv)

[0.84040688 0.37173732 0.75590216 0.17137779 0.3409862  0.69723953
 0.13817366 0.73715669 0.16658166 0.81563193]
[0.91691872 0.55581629 0.14783505 0.70113475 0.6478404  0.79748771
 0.61803803 0.68194351 0.96558455 0.06904475]
[[0.77058481 0.46711183 0.1242416  0.58923847 0.54444953 0.67021416
  0.51940341 0.57311002 0.8114839  0.05802568]
 [0.34085291 0.20661766 0.05495581 0.26063795 0.24082645 0.29645594
  0.2297478  0.25350385 0.35894382 0.02566651]
 [0.69310084 0.42014273 0.11174883 0.52998927 0.48970395 0.60282268
  0.46717628 0.51548257 0.72988744 0.05219107]
 [0.15713951 0.09525457 0.02533565 0.12015893 0.11102546 0.13667168
  0.10591799 0.11686997 0.16547975 0.01183274]
 [0.31265663 0.18952568 0.05040971 0.23907727 0.22090463 0.2719323
  0.21074244 0.23253332 0.329251   0.02354331]
 [0.63931198 0.38753709 0.10307644 0.48885886 0.45169993 0.55603995
  0.43092054 0.47547797 0.67324372 0.04814073]
 [0.12669402 0.07679917 0.02042691 0.09687836 0.08951448 0.1101918
  0.08539658 0.094

7. Vypočítejte hodnost matice o velikosti 5x6 naplněnou hodnotami 0, 1, 2, 3 ... . Byly by jste schopni zdůvodnit proč je hodnost taková jaká je?


In [132]:
A = np.reshape(np.arange(1, 31), (5, 6))
print(A)
print(np.linalg.matrix_rank(A))

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]
2



## Funkce nad poli
1. Vytvořte pole 10x10 s náhodnými hodnotami a najděte minimální a maximální hodnoty.


In [138]:
pole = np.random.rand(10, 10)
print(pole)

print(pole.min())
print(pole.max())

[[0.89392467 0.99739185 0.24554491 0.02940449 0.62985709 0.33632713
  0.3021893  0.83509812 0.8127299  0.42269599]
 [0.06116517 0.49267985 0.70231271 0.37568374 0.53615944 0.8472891
  0.52111243 0.13263777 0.90194024 0.91896013]
 [0.13945025 0.23829925 0.66587543 0.94061675 0.68083801 0.1910811
  0.47824633 0.87955786 0.99936606 0.19901586]
 [0.89328322 0.2461641  0.6163858  0.76666593 0.49789424 0.69291075
  0.22047731 0.99220911 0.6980914  0.69936143]
 [0.07908471 0.59117152 0.99062409 0.7973333  0.11147828 0.77850221
  0.39235351 0.97362783 0.3624768  0.69815604]
 [0.07150425 0.68983059 0.17045026 0.33556527 0.34429242 0.41828475
  0.42879926 0.6709893  0.45291994 0.02480647]
 [0.76859565 0.10031037 0.28301579 0.57221579 0.37421996 0.11595015
  0.76647141 0.77773132 0.39278355 0.39699785]
 [0.76967205 0.66310881 0.77946599 0.75903567 0.95583778 0.68273914
  0.97998984 0.94691235 0.119659   0.70462068]
 [0.33653618 0.68459725 0.86190304 0.89031176 0.90247241 0.82047146
  0.82703046 0

2. Vytvořte náhodný vektor o velikosti 30 a najděte střední hodnotu.



In [139]:
vektor = np.random.rand(30)
print(vektor.mean())

0.43437202385401336


3. Uvažujme celočíselný vektor Z, které z těchto výrazů jsou platné?
   ```python
   Z**Z
   2 << Z >> 2
   Z <- Z
   1j*Z
   Z/1/1
   Z<Z>Z
   ```



In [151]:
Z = np.random.randint(0, 7, 10)
print(Z)

print(Z**Z)
print(2 << Z >> 2)
print(Z < -Z)
print(1j * Z)
print(Z/1/1)
print(Z<Z>Z)

[6 2 6 0 0 0 5 3 1 3]
[46656     4 46656     1     1     1  3125    27     1    27]
[32  2 32  0  0  0 16  4  1  4]
[False False False False False False False False False False]
[0.+6.j 0.+2.j 0.+6.j 0.+0.j 0.+0.j 0.+0.j 0.+5.j 0.+3.j 0.+1.j 0.+3.j]
[6. 2. 6. 0. 0. 0. 5. 3. 1. 3.]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

4. Jaký je výsledek následujícího výrazu? 
   ```python
   0 * np.nan
   np.nan == np.nan
   np.inf > np.nan
   np.nan - np.nan
   np.nan in set([np.nan])
   0.3 == 3 * 0.1
   ```


In [159]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in {np.nan})
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


5. Jaké jsou výsledky následujících výrazů?
   ```python
   np.array(0) / np.array(0)
   np.array(0) // np.array(0)
   np.array([np.nan]).astype(int).astype(float)
   ```


In [160]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/tmp/ipykernel_4041/3912170336.py:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
/tmp/ipykernel_4041/3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))



6. Jak najít společné (stejné) hodnoty mezi dvěma poli? 


In [169]:
set([1, 2, 3, 5, 3]) & set([3, 5, 4, 7, 3, 2, 2, 1])

{1, 2, 3, 5}


7. Jak vypočítat ((A+B)*(-A/2)) přímo v poli (bez kopírování)?



In [178]:
A = np.random.rand(5, 5)
B = np.random.rand(5, 5)
print((A+B)*(-A/2))

[[-0.00443753 -0.53208887 -0.60247543 -0.02726669 -0.64934572]
 [-0.19879503 -0.70594194 -0.03570243 -0.01929054 -0.13398392]
 [-0.25837217 -0.20115873 -0.05796958 -0.42104271 -0.16661653]
 [-0.07963898 -0.08861204 -0.18514277 -0.00262844 -0.0348363 ]
 [-0.0324163  -0.25041065 -0.7490399  -0.4899639  -0.0963724 ]]



8. Vytvořte náhodný vektor o velikosti 10 a seřaďte ho.


In [175]:
v = np.random.rand(10)
print(np.sort(v))

[0.00275579 0.04621136 0.10772096 0.20074003 0.33226862 0.3763303
 0.4478917  0.52534275 0.55939483 0.99069563]



9. Vezměme daný vektor, jak přidat 1 ke každému prvku indexovanému druhým vektorem (dejte pozor na opakované indexy)? 



In [176]:
v[[1, 6, 3]] += 1
print(v)

[0.99069563 1.00275579 0.4478917  1.3763303  0.52534275 0.55939483
 1.10772096 0.04621136 0.33226862 0.20074003]
